version: "1.0.0.{build}-{branch}"

image: Visual Studio 2015
platform: x64

clone_folder: c:\projects\powershellmodules

environment:
  apikey:
    secure: va5y0yl54j06dyQqLoczP/9t/YyWPBTpBIh/12tw+PmfKID3YL6AIcSKh7VSQRC4

install:
  - ps: $nugetdir = Join-Path -Path $env:ProgramData -ChildPath 'Microsoft\Windows\PowerShell\PowerShellGet'
  - ps: mkdir $nugetdir
  - ps: Invoke-WebRequest -Uri 'https://dist.nuget.org/win-x86-commandline/v3.4.4/NuGet.exe' -OutFile "$nugetdir\nuget.exe"
  - ps: Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
  - ps: Install-Module -Name PSScriptAnalyzer
  - ps: Install-Module -Name BuildHelpers

build_script:
  - ps: Invoke-ScriptAnalyzer -Path c:\projects\powershellmodules -Recurse

deploy_script:
  - ps: .\publish.ps1

